// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewMessage struct {
	Content string `json:"content"`
	RoomID  string `json:"roomId"`
}

type NewRoom struct {
	Name         string   `json:"name"`
	MembersEmail []string `json:"membersEmail"`
}

type NewUser struct {
	Name                 string `json:"name"`
	Email                string `json:"email"`
	Password             string `json:"password"`
	PasswordConfirmation string `json:"passwordConfirmation"`
}

type Query struct {
}

type Subscription struct {
}
