// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewMessage struct {
	Content string `json:"content"`
	RoomID  string `json:"roomId"`
}

type NewRoom struct {
	Name         string   `json:"name"`
	MembersEmail []string `json:"membersEmail"`
}

type NewUser struct {
	Name                 string `json:"name"`
	Email                string `json:"email"`
	Password             string `json:"password"`
	PasswordConfirmation string `json:"passwordConfirmation"`
}

type Query struct {
}

type Subscription struct {
}

type TypingEvent struct {
	RoomID string `json:"roomId"`
	User   *User  `json:"user"`
	Typing bool   `json:"typing"`
}

type UpdateLastReadMessage struct {
	RoomID            string `json:"roomId"`
	UserID            string `json:"userId"`
	LastReadMessageID string `json:"lastReadMessageId"`
}

type UpdateMessageReceipt struct {
	MessageID string     `json:"messageId"`
	UserID    string     `json:"userId"`
	Status    string     `json:"status"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}
