package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/lafathalfath/go-chatserver/graph"
	"github.com/lafathalfath/go-chatserver/graph/models"
	"github.com/lafathalfath/go-chatserver/services"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input models.NewUser) (*models.User, error) {
	return services.UserServices().CreateUser(&input)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input models.Login) (bool, error) {
	return services.AuthServices().Login(ctx, &input)
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	return services.AuthServices().Logout(ctx)
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context) (bool, error) {
	return services.AuthServices().Refresh(ctx)
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input models.NewMessage) (*models.Message, error) {
	return services.MessageServices().SendMessage(ctx, &input)
}

// MarkRoomRead is the resolver for the markRoomRead field.
func (r *mutationResolver) MarkRoomRead(ctx context.Context, roomID string, lastMessageID string) (bool, error) {
	panic(fmt.Errorf("not implemented: MarkRoomRead - markRoomRead"))
}

// Typing is the resolver for the typing field.
func (r *mutationResolver) Typing(ctx context.Context, roomID string, isTyping bool) (bool, error) {
	return services.RoomServices().Typing(ctx, roomID, isTyping)
}

// CreateDm is the resolver for the createDM field.
func (r *mutationResolver) CreateDm(ctx context.Context, email string) (*models.Room, error) {
	return services.RoomServices().CreateDM(ctx, email)
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input models.NewRoom) (*models.Room, error) {
	return services.RoomServices().CreateGroup(ctx, &input)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*models.User, error) {
	return services.UserServices().GetUsers()
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
	return services.UserServices().GetUser(id)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	return services.AuthServices().Me(ctx)
}

// MyRooms is the resolver for the myRooms field.
func (r *queryResolver) MyRooms(ctx context.Context) ([]*models.Room, error) {
	return services.RoomServices().MyRooms(ctx)
}

// MyRoom is the resolver for the myRoom field.
func (r *queryResolver) MyRoom(ctx context.Context, id string) (*models.Room, error) {
	return services.RoomServices().MyRoom(ctx, id)
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, roomID string) ([]*models.Message, error) {
	return services.MessageServices().GetMessages(roomID)
}

// MessageReceived is the resolver for the messageReceived field.
func (r *subscriptionResolver) MessageReceived(ctx context.Context, roomID string) (<-chan *models.Message, error) {
	return services.MessageServices().SubscribeMessage(ctx, roomID)
}

// UserTyping is the resolver for the userTyping field.
func (r *subscriptionResolver) UserTyping(ctx context.Context, roomID string) (<-chan *models.TypingEvent, error) {
	return services.RoomServices().SubscribeUserTyping(ctx, roomID)
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

// Subscription returns graph.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graph.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
